CREATE TABLE PASSENGER (
    ID NUMBER,
    CONSTRAINT PASSENGER_PK PRIMARY KEY(ID),
    LAST_NAME NVARCHAR2(50),
    NATIONALITY NVARCHAR2(50),
    DATE_OF_BIRTH TIMESTAMP,
    PASSPORT_CODE NVARCHAR2(20)
);

CREATE SEQUENCE PASSENGER_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;