CREATE TABLE USERS (
    ID NUMBER,
    CONSTRAINT USERS_PK PRIMARY KEY(ID),
    FIRST_NAME NVARCHAR2(50),
    LAST_NAME NVARCHAR2(50),
    USER_NAME NVARCHAR2(50),
    PASSWORD NVARCHAR2(50)
);

CREATE SEQUENCE USERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;