CREATE TABLE ADVERTISEMENT (
    ID NUMBER,
    CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY(ID),
    USER_ID NUMBER NOT NULL,
    CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    TITLE NVARCHAR2(100),
    DESCRIPTION NVARCHAR2(200),
    PRICE NUMBER,
    CURRENCY NVARCHAR2(5),
    CATEGORY NVARCHAR2(20),
    SUBCATEGORY NVARCHAR2(20),
    CITY NVARCHAR2(50),
    PHONE NVARCHAR2(50),
    DATE_CREATED TIMESTAMP,
    DATE_EXPIRED TIMESTAMP
);

CREATE SEQUENCE ADV_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;