CREATE TABLE STORAGE (
    ID NUMBER NOT NULL ENABLE,
    CONSTRAINT STORAGE_PK PRIMARY KEY (ID),
    FORMATS_SUPPORTED NVARCHAR2(100),
    STORAGE_COUNTRY NVARCHAR2(20),
    STORAGE_MAX_SIZE NUMBER
);