CREATE TABLE FLIGHT_PASSENGER (
    FLIGHT_ID NUMBER NOT NULL,
    CONSTRAINT FLIGHT_FK FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHT(ID),
    PASSENGER_ID NUMBER NOT NULL,
    CONSTRAINT PASSENGER_FK FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(ID)
);