CREATE TABLE USERS (
    ID NUMBER,
    CONSTRAINT USERS_PK PRIMARY KEY(ID),
    USER_NAME NVARCHAR2(50) UNIQUE,
    PASSWORD NVARCHAR2(50) NOT NULL,
    FIRST_NAME NVARCHAR2(50) NOT NULL,
    LAST_NAME NVARCHAR2(50) NOT NULL
);

CREATE SEQUENCE USERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1;